### ISSUE TITLE
Question regarding User#_id

### ISSUE THREAD

**Issue by Paraxdev** [janderedev/automod#1]
Why is it `_id` and not just `id`?

**Comment by sussycatgirl** [comment]
Not sure what part you mean, but Revolt's API generally returns `_id` instead of `id` for objects. I think that's because Revolt uses mongodb as database, which uses `_id` as identifier for db entries (?).

**Comment by Codeize** [comment]
`_id` comes as a standard identifier with each entry into a MongoDB document, it'd be fairly counter-productive to add another `id` field when it already exists.

**Comment by Paraxdev** [comment]
> `_id` comes as a standard identifier with each entry into a MongoDB document, it'd be fairly counter-productive to add another `id` field when it already exists.

yeah makes sense then I were a bit irritated

**Comment by sussycatgirl** [comment]
> it'd be fairly counter-productive to add another `id` field when it already exists.

On that note, Automod sets 2 separate id fields on some database entries. Thanks for reminding me to fix that, I guess?
