### ISSUE TITLE
Feature request : spoiler revolt to discord

### ISSUE THREAD

**Issue by Sammie26559** [janderedev/automod#21]
Hello,
is it possible to convert discord spoiler `||` to revolt spoiler `!!` ?

**Comment by Chirunos** [comment]
Discord spoilers to Revolt spoilers and vice-versa is already a thing (at least works with me)

**Comment by sussycatgirl** [comment]
Oops, forgot to close this issue. Yeah, it's been a thing for a while, ||discord spoilers|| are translated to !!revolt spoilers!! and vice versa.
