### ISSUE TITLE
feat: Bridge masquerades

### ISSUE THREAD

**Issue by Derpius** [janderedev/automod#25]
Revolt message from bot without masquerade, and message with
![Revolt](https://user-images.githubusercontent.com/49565664/189544257-705fd2be-5563-490e-97b0-1780745a84af.png)

Same messages in Discord
![Discord](https://user-images.githubusercontent.com/49565664/189544270-76e854ae-7666-488b-8284-594375892ba7.png)

**Comment by sussycatgirl** [comment]
Forgot that there's an open issue about this, but this is implemented now, though it's not enabled by default - You can enable it on a per-channel basis with `/bridge config`
