### ISSUE TITLE
[Bug] automod on discord side won't bridge

### ISSUE THREAD

**Issue by 4cecoder** [janderedev/automod#26]
<img width="338" alt="Screen Shot 2022-10-12 at 9 39 00 PM" src="https://user-images.githubusercontent.com/88108711/195478846-1abeedfe-3e4a-4f24-91b6-fc5cc2001484.png">

always recieving this message on `/bridge confirm {id}` on the discord side

**Comment by searinminecraft** [comment]
automod for some reason does that, but it actually bridged in the background. to confirm, execute `/bridge list` on the revolt side and see if it bridged or not

**Comment by 4cecoder** [comment]
it gets bridged and sometimes it just needs to be retried to confirm that its all synced. 

although the bug may be repeatable we may not need to track this.
